---
title: "project_map_2DCNN"
author: "EBellis"
date: "3/3/2021"
output: html_document
---
This code will project a map of yield projections using model weights trained from a 2DCNN
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = '~/Documents/GitHub/XASU_rice/1_process_TIF_layers/')
```

## R code to process input image (downsample, mask many of the NA's, create raster stack)
```{r}
library(raster)
library(rgdal)
library(sf)
library(stringr)
library(ggplot2)

#setwd('~/Documents/GitHub/XASU_rice/1_process_TIF_layers/')
source('~/Documents/GitHub/XASU_rice/1_process_TIF_layers/get_max_val.R')
source('~/Documents/GitHub/XASU_rice/1_process_TIF_layers/process_VIs.R')
source('~/Documents/GitHub/XASU_rice/1_process_TIF_layers/output_labels.R')
source('~/Documents/GitHub/XASU_rice/1_process_TIF_layers/create_daystack.R')
source('~/Documents/GitHub/XASU_rice/1_process_TIF_layers/output_images.R')

path_to <- "/Volumes/ABISSD/"

## get yield data layer, downsample, mask; base all other layers on this layer
yld <- raster(paste0(path_to,'Yield.tif')) # utm, 5 cm resolution
yld.5 <- aggregate(yld, 10) # 0.5 x 0.5 m resolution
crop_extent <- readOGR(paste0(path_to,"04-11-2019/Carr_N_Without_Ditch.shp"))
yld.5d <- crop(yld.5, crop_extent)
yld.5dm <- mask(yld.5d, crop_extent) # 5616 cells; 5235 of these are non-NA

## process all other layers (downsample, crop, mask); make raster stacks for each day; split into test, train, and validation sets; split each of these into 5x5 pixel subimages and then save each image and channel separately as .csv file 
flydays <- c("04-11-2019","05-21-2019","06-13-2019","06-29-2019","07-11-2019","08-01-2019", "08-13-2019", "08-21-2019","08-28-2019","09-07-2019","09-13-2019") 
channels <- c("CIgreen.tif","GNDVI.tif","NAVI.tif","NDVI.tif","RENDVI.tif","TGI.tif","Thermal.tif")
path_to_raster <- "/Volumes/ABISSD/"
vis.list <- str_replace(channels, '.tif', '')

############################### output project for 1 day
j = 6
daystack <- create_daystack(path_to_raster, flydays[j], channels, yld.5dm) # raster stack for a single day
  
# mask so all have same number of NA's and number of images is same
mostnas_idx <- which.max(as.matrix(cellStats(daystack, stat='countNA')))
yld.dayna <- mask(yld.5dm, daystack[[mostnas_idx]])
daystack <- mask(daystack, daystack[[mostnas_idx]])

```

## Create a new raster with model predictions
```{r}
# create a new raster layer with extent of the yield layer, fill with NA's
pred_yld <- yld.5dm
values(pred_yld) <- NA
pred_yld
```
# this is going to involve some python
```{r}
library(reticulate)

use_python('/Users/ebellis/Library/r-miniconda/envs/r-reticulate_rice/bin/python', required = T)
use_condaenv("r-reticulate_rice", required = T)
reticulate::py_config() # had to change .Renviron file to get python version from conda env and load packages

repl_python()

```

```{python}
import numpy, sys
import tensorflow as tf
tf.version
```

```{r}
# get 5x5 section of image
crop(daystack, extent(daystack, 500,505,500,505)) # crop using row and column numbers

```

