---
title: "R Notebook"
output: html_notebook
---
This script produces Figure 2, a summary of the model performance across all folds
```{r}
library(lubridate)
library(ggplot2)
library(tidyverse)
library(wesanderson)

rice <- read.csv('rice_remote_sensing - Sheet1.csv', header=T)
rice$Date <- as.Date(rice$Date, "%m-%d-%Y")
rice <- subset(rice, Date != "2019-06-13")
#rice.long <- rice %>% pivot_longer(c(Train_MSE, Val_MSE))
rice.long <- rice %>% pivot_longer(c(Train_MSE, Val_MSE, Test_MSE))
rice$id <- paste0(rice$Model, rice$Date, sep="_")
rice.long$id <- paste0(rice.long$Model, rice.long$Date, sep="_")
rice.long$name <- factor(rice.long$name,      # Reordering group factor levels
                         levels = c("Test_MSE", "Val_MSE", "Train_MSE"),
                         labels = c("Test","Validation","Train"))

# all in one panel
fig2 <- ggplot(rice.long, aes(x=Date, y=value, color = Model, group=id, pch = Set)) + 
  geom_point(position = position_dodge(width = 5), size = 1.1, alpha = 0.5) +
  theme_light() +
  theme(panel.grid.minor.x = element_blank()) +
  geom_line(position = position_dodge(width = 5), size = 0.3) +
  scale_color_manual(values = wes_palette("Zissou1", 5, type = c("discrete"))) +
  facet_grid(name~.) +
  labs(shape = "Fold") +
  ylab("MSE")

# save figure to file
pdf(file = "Fig2_allmods.pdf", width = 7.07, height = 4)
fig2
dev.off()
```

## get summary stats 
```{r}
yld_stats <- rice.long %>% 
  #filter(name == "Train") %>%
  select(Model, Set, Date, name, value) %>%
  group_by(Model, Date, name) %>%
  summarize(mean_yld = mean(value), sd_yld = sd(value))

fig3 <- ggplot(yld_stats, aes(x=Date, y=mean_yld, color=Model)) + 
  geom_point(alpha = 0.7, size=0.7) + 
  geom_line() +
  theme_light() +
  theme(panel.grid.minor.x = element_blank()) +
  ylab("Average MSE") +
  facet_grid(name~.) +
  scale_color_manual(values = wes_palette("Zissou1", 5, type = c("discrete")))

pdf(file = "Fig2b_allmods.pdf", width = 3.5, height = 3)
fig3
dev.off()


ggplot(yld_stats, aes(x=Date, y=sd_yld, color=Model)) + 
  geom_point(alpha = 0.7, size=0.7) + 
  geom_line() +
  theme_light() +
  theme(panel.grid.minor.x = element_blank()) +
  ylab("Average MSE") +
  facet_grid(name~.) +
  scale_color_manual(values = wes_palette("Zissou1", 5, type = c("discrete")))
```

